backend:
  name: github
  repo: nilocesar/portfolio2023
  base_url: https://portfolio2023-murex-two.vercel.app/
  auth_endpoint: api/auth/ # Essa rota vai ser muito importante mais para frente

media_folder: public/assets/img
public_folder: /assets/img

publish_mode: editorial_workflow # Isso permite ter aquele workflow com drafts e tudo

slug:
  encoding: 'ascii'
  clean_accents: true

collections:
  - name: 'project' # Used in routes, e.g., /admin/collections/project
    label: 'Project' # Used in the UI
    folder: '_posts/project' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'project' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Imagem do Card', name: 'card', widget: 'image' }
      - { label: 'Imagem do Projeto', name: 'thumbnail', widget: 'image' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descrição', name: 'body', widget: 'markdown' }
  - name: 'about' # Used in routes, e.g., /admin/collections/about
    label: 'About' # Used in the UI
    folder: '_posts/about' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Avatar', name: 'avatar', widget: 'image' }
      - { label: 'Descrição', name: 'body', widget: 'markdown' }
